apiVersion: 1

datasources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      isDefault: true

    - name: Jaeger
      type: jaeger
      access: proxy
      url: http://jaeger:16686

    - name: VictoriaMetrics
      type: prometheus
      access: proxy
      url: http://victoriametrics:8428

#    - name: VictoriaMetrics - cluster
#      type: prometheus
#      access: proxy
#      url: http://vmselect:8481/select/0/prometheus
#      isDefault: false
